CRITICAL - 2025-04-12 13:34:39 --> CodeIgniter\Filters\Exceptions\FilterException: "authFilter" filter must have a matching alias defined.
[Method: POST, Route: leads]
in SYSTEMPATH/Filters/Filters.php on line 590.
 1 SYSTEMPATH/Filters/Filters.php(590): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('authFilter')
 2 SYSTEMPATH/Filters/Filters.php(641): CodeIgniter\Filters\Filters->enableFilter('authFilter', 'before')
 3 SYSTEMPATH/CodeIgniter.php(467): CodeIgniter\Filters\Filters->enableFilters([...], 'before')
 4 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-12 13:35:51 --> TypeError: Key material must be a string, resource, or OpenSSLAsymmetricKey
[Method: POST, Route: leads]
in VENDORPATH/firebase/php-jwt/src/Key.php on line 26.
 1 APPPATH/Filters/AuthFilter.php(51): Firebase\JWT\Key->__construct(false, 'HS256')
 2 SYSTEMPATH/Filters/Filters.php(241): App\Filters\AuthFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 3 SYSTEMPATH/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore([...])
 4 SYSTEMPATH/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
 5 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-12 13:40:17 --> TypeError: Key material must be a string, resource, or OpenSSLAsymmetricKey
[Method: POST, Route: leads]
in VENDORPATH/firebase/php-jwt/src/Key.php on line 26.
 1 APPPATH/Filters/AuthFilter.php(51): Firebase\JWT\Key->__construct(false, 'HS256')
 2 SYSTEMPATH/Filters/Filters.php(241): App\Filters\AuthFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 3 SYSTEMPATH/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore([...])
 4 SYSTEMPATH/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
 5 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-12 13:42:11 --> CodeIgniter\Database\Exceptions\DataException: There is no data to insert.
[Method: POST, Route: leads]
in SYSTEMPATH/BaseModel.php on line 1830.
 1 SYSTEMPATH/BaseModel.php(1830): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH/BaseModel.php(805): CodeIgniter\BaseModel->transformDataToArray([], 'insert')
 3 SYSTEMPATH/Model.php(800): CodeIgniter\BaseModel->insert([], true)
 4 APPPATH/Controllers/Leads.php(39): CodeIgniter\Model->insert([])
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Leads->create()
 6 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Leads))
 7 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-12 14:42:53 --> CodeIgniter\Validation\Exceptions\ValidationException: "json" is not a valid rule.
[Method: POST, Route: leads]
in SYSTEMPATH/Validation/Validation.php on line 346.
 1 SYSTEMPATH/Validation/Validation.php(346): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('json')
 2 SYSTEMPATH/Validation/Validation.php(202): CodeIgniter\Validation\Validation->processRules('extra', 'extra', [...], [...], [...], 'extra')
 3 SYSTEMPATH/BaseModel.php(1576): CodeIgniter\Validation\Validation->run([...], null, null)
 4 SYSTEMPATH/BaseModel.php(808): CodeIgniter\BaseModel->validate([...])
 5 SYSTEMPATH/Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH/Controllers/Leads.php(39): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Leads->create()
 8 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Leads))
 9 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-12 14:47:58 --> CodeIgniter\Validation\Exceptions\ValidationException: "json" is not a valid rule.
[Method: POST, Route: leads]
in SYSTEMPATH/Validation/Validation.php on line 346.
 1 SYSTEMPATH/Validation/Validation.php(346): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('json')
 2 SYSTEMPATH/Validation/Validation.php(202): CodeIgniter\Validation\Validation->processRules('extra', 'extra', '{"address":"123 Main St, Springfield, IL","city":"Springfield","state":"IL","zip":"62701"}', [...], [...], 'extra')
 3 SYSTEMPATH/BaseModel.php(1576): CodeIgniter\Validation\Validation->run([...], null, null)
 4 SYSTEMPATH/BaseModel.php(808): CodeIgniter\BaseModel->validate([...])
 5 SYSTEMPATH/Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH/Controllers/Leads.php(46): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Leads->create()
 8 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Leads))
 9 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-12 17:09:25 --> CodeIgniter\Exceptions\CriticalError: Cache: RedisException occurred with message (Connection refused). in /var/www/api/system/Cache/Handlers/RedisHandler.php:101
Stack trace:
#0 /var/www/api/system/Cache/CacheFactory.php(81): CodeIgniter\Cache\Handlers\RedisHandler->initialize()
#1 /var/www/api/system/Config/Services.php(129): CodeIgniter\Cache\CacheFactory::getHandler(Object(Config\Cache))
#2 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::cache(Object(Config\Cache), false)
#3 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#4 /var/www/api/system/Config/Services.php(124): CodeIgniter\Config\BaseService::getSharedInstance('cache', NULL)
#5 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::cache()
#6 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#7 /var/www/api/system/Config/Services.php(454): CodeIgniter\Config\BaseService::get('cache')
#8 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::responsecache(Object(Config\Cache), NULL, false)
#9 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#10 /var/www/api/system/Config/Services.php(450): CodeIgniter\Config\BaseService::getSharedInstance('responsecache', NULL, NULL)
#11 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::responsecache()
#12 /var/www/api/system/CodeIgniter.php(178): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#13 /var/www/api/system/Config/Services.php(164): CodeIgniter\CodeIgniter->__construct(Object(Config\App))
#14 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::codeigniter(Object(Config\App), false)
#15 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#16 /var/www/api/system/Config/Services.php(159): CodeIgniter\Config\BaseService::getSharedInstance('codeigniter', NULL)
#17 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::codeigniter()
#18 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#19 /var/www/api/system/Common.php(1000): CodeIgniter\Config\BaseService::get('codeigniter')
#20 /var/www/api/system/Boot.php(320): service('codeigniter')
#21 /var/www/api/system/Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
#22 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#23 {main} Resorting to using dummy handler.
CRITICAL - 2025-04-12 17:09:30 --> CodeIgniter\Exceptions\CriticalError: Cache: RedisException occurred with message (Connection refused). in /var/www/api/system/Cache/Handlers/RedisHandler.php:101
Stack trace:
#0 /var/www/api/system/Cache/CacheFactory.php(81): CodeIgniter\Cache\Handlers\RedisHandler->initialize()
#1 /var/www/api/system/Config/Services.php(129): CodeIgniter\Cache\CacheFactory::getHandler(Object(Config\Cache))
#2 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::cache(Object(Config\Cache), false)
#3 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#4 /var/www/api/system/Config/Services.php(124): CodeIgniter\Config\BaseService::getSharedInstance('cache', NULL)
#5 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::cache()
#6 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#7 /var/www/api/system/Config/Services.php(454): CodeIgniter\Config\BaseService::get('cache')
#8 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::responsecache(Object(Config\Cache), NULL, false)
#9 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#10 /var/www/api/system/Config/Services.php(450): CodeIgniter\Config\BaseService::getSharedInstance('responsecache', NULL, NULL)
#11 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::responsecache()
#12 /var/www/api/system/CodeIgniter.php(178): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#13 /var/www/api/system/Config/Services.php(164): CodeIgniter\CodeIgniter->__construct(Object(Config\App))
#14 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::codeigniter(Object(Config\App), false)
#15 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#16 /var/www/api/system/Config/Services.php(159): CodeIgniter\Config\BaseService::getSharedInstance('codeigniter', NULL)
#17 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::codeigniter()
#18 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#19 /var/www/api/system/Common.php(1000): CodeIgniter\Config\BaseService::get('codeigniter')
#20 /var/www/api/system/Boot.php(320): service('codeigniter')
#21 /var/www/api/system/Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
#22 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#23 {main} Resorting to using dummy handler.
CRITICAL - 2025-04-12 17:09:47 --> CodeIgniter\Exceptions\CriticalError: Cache: RedisException occurred with message (Connection refused). in /var/www/api/system/Cache/Handlers/RedisHandler.php:101
Stack trace:
#0 /var/www/api/system/Cache/CacheFactory.php(81): CodeIgniter\Cache\Handlers\RedisHandler->initialize()
#1 /var/www/api/system/Config/Services.php(129): CodeIgniter\Cache\CacheFactory::getHandler(Object(Config\Cache))
#2 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::cache(Object(Config\Cache), false)
#3 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#4 /var/www/api/system/Config/Services.php(124): CodeIgniter\Config\BaseService::getSharedInstance('cache', NULL)
#5 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::cache()
#6 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#7 /var/www/api/system/Config/Services.php(454): CodeIgniter\Config\BaseService::get('cache')
#8 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::responsecache(Object(Config\Cache), NULL, false)
#9 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#10 /var/www/api/system/Config/Services.php(450): CodeIgniter\Config\BaseService::getSharedInstance('responsecache', NULL, NULL)
#11 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::responsecache()
#12 /var/www/api/system/CodeIgniter.php(178): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#13 /var/www/api/system/Config/Services.php(164): CodeIgniter\CodeIgniter->__construct(Object(Config\App))
#14 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::codeigniter(Object(Config\App), false)
#15 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#16 /var/www/api/system/Config/Services.php(159): CodeIgniter\Config\BaseService::getSharedInstance('codeigniter', NULL)
#17 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::codeigniter()
#18 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#19 /var/www/api/system/Common.php(1000): CodeIgniter\Config\BaseService::get('codeigniter')
#20 /var/www/api/system/Boot.php(320): service('codeigniter')
#21 /var/www/api/system/Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
#22 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#23 {main} Resorting to using dummy handler.
CRITICAL - 2025-04-12 17:10:34 --> CodeIgniter\Exceptions\CriticalError: Cache: RedisException occurred with message (Connection refused). in /var/www/api/system/Cache/Handlers/RedisHandler.php:101
Stack trace:
#0 /var/www/api/system/Cache/CacheFactory.php(81): CodeIgniter\Cache\Handlers\RedisHandler->initialize()
#1 /var/www/api/system/Config/Services.php(129): CodeIgniter\Cache\CacheFactory::getHandler(Object(Config\Cache))
#2 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::cache(Object(Config\Cache), false)
#3 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#4 /var/www/api/system/Config/Services.php(124): CodeIgniter\Config\BaseService::getSharedInstance('cache', NULL)
#5 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::cache()
#6 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#7 /var/www/api/system/Config/Services.php(454): CodeIgniter\Config\BaseService::get('cache')
#8 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::responsecache(Object(Config\Cache), NULL, false)
#9 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#10 /var/www/api/system/Config/Services.php(450): CodeIgniter\Config\BaseService::getSharedInstance('responsecache', NULL, NULL)
#11 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::responsecache()
#12 /var/www/api/system/CodeIgniter.php(178): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#13 /var/www/api/system/Config/Services.php(164): CodeIgniter\CodeIgniter->__construct(Object(Config\App))
#14 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::codeigniter(Object(Config\App), false)
#15 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#16 /var/www/api/system/Config/Services.php(159): CodeIgniter\Config\BaseService::getSharedInstance('codeigniter', NULL)
#17 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::codeigniter()
#18 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#19 /var/www/api/system/Common.php(1000): CodeIgniter\Config\BaseService::get('codeigniter')
#20 /var/www/api/system/Boot.php(320): service('codeigniter')
#21 /var/www/api/system/Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
#22 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#23 {main} Resorting to using dummy handler.
CRITICAL - 2025-04-12 17:11:12 --> CodeIgniter\Exceptions\CriticalError: Cache: RedisException occurred with message (Connection refused). in /var/www/api/system/Cache/Handlers/RedisHandler.php:101
Stack trace:
#0 /var/www/api/system/Cache/CacheFactory.php(81): CodeIgniter\Cache\Handlers\RedisHandler->initialize()
#1 /var/www/api/system/Config/Services.php(129): CodeIgniter\Cache\CacheFactory::getHandler(Object(Config\Cache))
#2 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::cache(Object(Config\Cache), false)
#3 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#4 /var/www/api/system/Config/Services.php(124): CodeIgniter\Config\BaseService::getSharedInstance('cache', NULL)
#5 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::cache()
#6 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#7 /var/www/api/system/Config/Services.php(454): CodeIgniter\Config\BaseService::get('cache')
#8 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::responsecache(Object(Config\Cache), NULL, false)
#9 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#10 /var/www/api/system/Config/Services.php(450): CodeIgniter\Config\BaseService::getSharedInstance('responsecache', NULL, NULL)
#11 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::responsecache()
#12 /var/www/api/system/CodeIgniter.php(178): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#13 /var/www/api/system/Config/Services.php(164): CodeIgniter\CodeIgniter->__construct(Object(Config\App))
#14 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::codeigniter(Object(Config\App), false)
#15 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#16 /var/www/api/system/Config/Services.php(159): CodeIgniter\Config\BaseService::getSharedInstance('codeigniter', NULL)
#17 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::codeigniter()
#18 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#19 /var/www/api/system/Common.php(1000): CodeIgniter\Config\BaseService::get('codeigniter')
#20 /var/www/api/system/Boot.php(320): service('codeigniter')
#21 /var/www/api/system/Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
#22 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#23 {main} Resorting to using dummy handler.
CRITICAL - 2025-04-12 17:11:37 --> CodeIgniter\Exceptions\CriticalError: Cache: RedisException occurred with message (Connection refused). in /var/www/api/system/Cache/Handlers/RedisHandler.php:101
Stack trace:
#0 /var/www/api/system/Cache/CacheFactory.php(81): CodeIgniter\Cache\Handlers\RedisHandler->initialize()
#1 /var/www/api/system/Config/Services.php(129): CodeIgniter\Cache\CacheFactory::getHandler(Object(Config\Cache))
#2 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::cache(Object(Config\Cache), false)
#3 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#4 /var/www/api/system/Config/Services.php(124): CodeIgniter\Config\BaseService::getSharedInstance('cache', NULL)
#5 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::cache()
#6 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#7 /var/www/api/system/Config/Services.php(454): CodeIgniter\Config\BaseService::get('cache')
#8 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::responsecache(Object(Config\Cache), NULL, false)
#9 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#10 /var/www/api/system/Config/Services.php(450): CodeIgniter\Config\BaseService::getSharedInstance('responsecache', NULL, NULL)
#11 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::responsecache()
#12 /var/www/api/system/CodeIgniter.php(178): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#13 /var/www/api/system/Config/Services.php(164): CodeIgniter\CodeIgniter->__construct(Object(Config\App))
#14 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::codeigniter(Object(Config\App), false)
#15 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#16 /var/www/api/system/Config/Services.php(159): CodeIgniter\Config\BaseService::getSharedInstance('codeigniter', NULL)
#17 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::codeigniter()
#18 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#19 /var/www/api/system/Common.php(1000): CodeIgniter\Config\BaseService::get('codeigniter')
#20 /var/www/api/system/Boot.php(320): service('codeigniter')
#21 /var/www/api/system/Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
#22 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#23 {main} Resorting to using dummy handler.
CRITICAL - 2025-04-12 17:14:06 --> CodeIgniter\Exceptions\CriticalError: Cache: RedisException occurred with message (NOAUTH Authentication required.). in /var/www/api/system/Cache/Handlers/RedisHandler.php:101
Stack trace:
#0 /var/www/api/system/Cache/CacheFactory.php(81): CodeIgniter\Cache\Handlers\RedisHandler->initialize()
#1 /var/www/api/system/Config/Services.php(129): CodeIgniter\Cache\CacheFactory::getHandler(Object(Config\Cache))
#2 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::cache(Object(Config\Cache), false)
#3 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#4 /var/www/api/system/Config/Services.php(124): CodeIgniter\Config\BaseService::getSharedInstance('cache', NULL)
#5 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::cache()
#6 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#7 /var/www/api/system/Config/Services.php(454): CodeIgniter\Config\BaseService::get('cache')
#8 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::responsecache(Object(Config\Cache), NULL, false)
#9 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#10 /var/www/api/system/Config/Services.php(450): CodeIgniter\Config\BaseService::getSharedInstance('responsecache', NULL, NULL)
#11 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::responsecache()
#12 /var/www/api/system/CodeIgniter.php(178): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#13 /var/www/api/system/Config/Services.php(164): CodeIgniter\CodeIgniter->__construct(Object(Config\App))
#14 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::codeigniter(Object(Config\App), false)
#15 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#16 /var/www/api/system/Config/Services.php(159): CodeIgniter\Config\BaseService::getSharedInstance('codeigniter', NULL)
#17 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::codeigniter()
#18 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#19 /var/www/api/system/Common.php(1000): CodeIgniter\Config\BaseService::get('codeigniter')
#20 /var/www/api/system/Boot.php(320): service('codeigniter')
#21 /var/www/api/system/Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
#22 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#23 {main} Resorting to using dummy handler.
CRITICAL - 2025-04-12 17:14:15 --> CodeIgniter\Exceptions\CriticalError: Cache: RedisException occurred with message (NOAUTH Authentication required.). in /var/www/api/system/Cache/Handlers/RedisHandler.php:101
Stack trace:
#0 /var/www/api/system/Cache/CacheFactory.php(81): CodeIgniter\Cache\Handlers\RedisHandler->initialize()
#1 /var/www/api/system/Config/Services.php(129): CodeIgniter\Cache\CacheFactory::getHandler(Object(Config\Cache))
#2 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::cache(Object(Config\Cache), false)
#3 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#4 /var/www/api/system/Config/Services.php(124): CodeIgniter\Config\BaseService::getSharedInstance('cache', NULL)
#5 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::cache()
#6 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#7 /var/www/api/system/Config/Services.php(454): CodeIgniter\Config\BaseService::get('cache')
#8 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::responsecache(Object(Config\Cache), NULL, false)
#9 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#10 /var/www/api/system/Config/Services.php(450): CodeIgniter\Config\BaseService::getSharedInstance('responsecache', NULL, NULL)
#11 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::responsecache()
#12 /var/www/api/system/CodeIgniter.php(178): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#13 /var/www/api/system/Config/Services.php(164): CodeIgniter\CodeIgniter->__construct(Object(Config\App))
#14 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::codeigniter(Object(Config\App), false)
#15 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#16 /var/www/api/system/Config/Services.php(159): CodeIgniter\Config\BaseService::getSharedInstance('codeigniter', NULL)
#17 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::codeigniter()
#18 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#19 /var/www/api/system/Common.php(1000): CodeIgniter\Config\BaseService::get('codeigniter')
#20 /var/www/api/system/Boot.php(320): service('codeigniter')
#21 /var/www/api/system/Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
#22 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#23 {main} Resorting to using dummy handler.
CRITICAL - 2025-04-12 17:14:20 --> CodeIgniter\Exceptions\CriticalError: Cache: RedisException occurred with message (NOAUTH Authentication required.). in /var/www/api/system/Cache/Handlers/RedisHandler.php:101
Stack trace:
#0 /var/www/api/system/Cache/CacheFactory.php(81): CodeIgniter\Cache\Handlers\RedisHandler->initialize()
#1 /var/www/api/system/Config/Services.php(129): CodeIgniter\Cache\CacheFactory::getHandler(Object(Config\Cache))
#2 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::cache(Object(Config\Cache), false)
#3 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#4 /var/www/api/system/Config/Services.php(124): CodeIgniter\Config\BaseService::getSharedInstance('cache', NULL)
#5 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::cache()
#6 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#7 /var/www/api/system/Config/Services.php(454): CodeIgniter\Config\BaseService::get('cache')
#8 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::responsecache(Object(Config\Cache), NULL, false)
#9 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#10 /var/www/api/system/Config/Services.php(450): CodeIgniter\Config\BaseService::getSharedInstance('responsecache', NULL, NULL)
#11 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::responsecache()
#12 /var/www/api/system/CodeIgniter.php(178): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#13 /var/www/api/system/Config/Services.php(164): CodeIgniter\CodeIgniter->__construct(Object(Config\App))
#14 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::codeigniter(Object(Config\App), false)
#15 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#16 /var/www/api/system/Config/Services.php(159): CodeIgniter\Config\BaseService::getSharedInstance('codeigniter', NULL)
#17 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::codeigniter()
#18 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#19 /var/www/api/system/Common.php(1000): CodeIgniter\Config\BaseService::get('codeigniter')
#20 /var/www/api/system/Boot.php(320): service('codeigniter')
#21 /var/www/api/system/Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
#22 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#23 {main} Resorting to using dummy handler.
CRITICAL - 2025-04-12 17:14:38 --> CodeIgniter\Exceptions\CriticalError: Cache: RedisException occurred with message (Connection refused). in /var/www/api/system/Cache/Handlers/RedisHandler.php:101
Stack trace:
#0 /var/www/api/system/Cache/CacheFactory.php(81): CodeIgniter\Cache\Handlers\RedisHandler->initialize()
#1 /var/www/api/system/Config/Services.php(129): CodeIgniter\Cache\CacheFactory::getHandler(Object(Config\Cache))
#2 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::cache(Object(Config\Cache), false)
#3 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#4 /var/www/api/system/Config/Services.php(124): CodeIgniter\Config\BaseService::getSharedInstance('cache', NULL)
#5 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::cache()
#6 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#7 /var/www/api/system/Config/Services.php(454): CodeIgniter\Config\BaseService::get('cache')
#8 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::responsecache(Object(Config\Cache), NULL, false)
#9 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#10 /var/www/api/system/Config/Services.php(450): CodeIgniter\Config\BaseService::getSharedInstance('responsecache', NULL, NULL)
#11 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::responsecache()
#12 /var/www/api/system/CodeIgniter.php(178): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#13 /var/www/api/system/Config/Services.php(164): CodeIgniter\CodeIgniter->__construct(Object(Config\App))
#14 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::codeigniter(Object(Config\App), false)
#15 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#16 /var/www/api/system/Config/Services.php(159): CodeIgniter\Config\BaseService::getSharedInstance('codeigniter', NULL)
#17 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::codeigniter()
#18 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#19 /var/www/api/system/Common.php(1000): CodeIgniter\Config\BaseService::get('codeigniter')
#20 /var/www/api/system/Boot.php(320): service('codeigniter')
#21 /var/www/api/system/Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
#22 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#23 {main} Resorting to using dummy handler.
CRITICAL - 2025-04-12 17:17:22 --> CodeIgniter\Exceptions\CriticalError: Cache: RedisException occurred with message (NOAUTH Authentication required.). in /var/www/api/system/Cache/Handlers/RedisHandler.php:101
Stack trace:
#0 /var/www/api/system/Cache/CacheFactory.php(81): CodeIgniter\Cache\Handlers\RedisHandler->initialize()
#1 /var/www/api/system/Config/Services.php(129): CodeIgniter\Cache\CacheFactory::getHandler(Object(Config\Cache))
#2 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::cache(Object(Config\Cache), false)
#3 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#4 /var/www/api/system/Config/Services.php(124): CodeIgniter\Config\BaseService::getSharedInstance('cache', NULL)
#5 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::cache()
#6 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#7 /var/www/api/system/Config/Services.php(454): CodeIgniter\Config\BaseService::get('cache')
#8 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::responsecache(Object(Config\Cache), NULL, false)
#9 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#10 /var/www/api/system/Config/Services.php(450): CodeIgniter\Config\BaseService::getSharedInstance('responsecache', NULL, NULL)
#11 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::responsecache()
#12 /var/www/api/system/CodeIgniter.php(178): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#13 /var/www/api/system/Config/Services.php(164): CodeIgniter\CodeIgniter->__construct(Object(Config\App))
#14 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::codeigniter(Object(Config\App), false)
#15 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#16 /var/www/api/system/Config/Services.php(159): CodeIgniter\Config\BaseService::getSharedInstance('codeigniter', NULL)
#17 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::codeigniter()
#18 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#19 /var/www/api/system/Common.php(1000): CodeIgniter\Config\BaseService::get('codeigniter')
#20 /var/www/api/system/Boot.php(320): service('codeigniter')
#21 /var/www/api/system/Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
#22 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#23 {main} Resorting to using dummy handler.
CRITICAL - 2025-04-12 17:17:26 --> CodeIgniter\Exceptions\CriticalError: Cache: RedisException occurred with message (NOAUTH Authentication required.). in /var/www/api/system/Cache/Handlers/RedisHandler.php:101
Stack trace:
#0 /var/www/api/system/Cache/CacheFactory.php(81): CodeIgniter\Cache\Handlers\RedisHandler->initialize()
#1 /var/www/api/system/Config/Services.php(129): CodeIgniter\Cache\CacheFactory::getHandler(Object(Config\Cache))
#2 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::cache(Object(Config\Cache), false)
#3 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#4 /var/www/api/system/Config/Services.php(124): CodeIgniter\Config\BaseService::getSharedInstance('cache', NULL)
#5 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::cache()
#6 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('cache', Array)
#7 /var/www/api/system/Config/Services.php(454): CodeIgniter\Config\BaseService::get('cache')
#8 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::responsecache(Object(Config\Cache), NULL, false)
#9 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#10 /var/www/api/system/Config/Services.php(450): CodeIgniter\Config\BaseService::getSharedInstance('responsecache', NULL, NULL)
#11 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::responsecache()
#12 /var/www/api/system/CodeIgniter.php(178): CodeIgniter\Config\BaseService::__callStatic('responsecache', Array)
#13 /var/www/api/system/Config/Services.php(164): CodeIgniter\CodeIgniter->__construct(Object(Config\App))
#14 /var/www/api/system/Config/BaseService.php(312): CodeIgniter\Config\Services::codeigniter(Object(Config\App), false)
#15 /var/www/api/system/Config/BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#16 /var/www/api/system/Config/Services.php(159): CodeIgniter\Config\BaseService::getSharedInstance('codeigniter', NULL)
#17 /var/www/api/system/Config/BaseService.php(321): CodeIgniter\Config\Services::codeigniter()
#18 /var/www/api/system/Config/BaseService.php(202): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#19 /var/www/api/system/Common.php(1000): CodeIgniter\Config\BaseService::get('codeigniter')
#20 /var/www/api/system/Boot.php(320): service('codeigniter')
#21 /var/www/api/system/Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
#22 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#23 {main} Resorting to using dummy handler.
CRITICAL - 2025-04-12 18:33:55 --> CodeIgniter\Exceptions\InvalidArgumentException: update(): argument #1 ($id) should not be boolean.
[Method: GET, Route: leads]
in SYSTEMPATH/BaseModel.php on line 989.
 1 SYSTEMPATH/Model.php(863): CodeIgniter\BaseModel->update(false, [...])
 2 APPPATH/Filters/LogsFilter.php(63): CodeIgniter\Model->update(false, [...])
 3 SYSTEMPATH/Filters/Filters.php(278): App\Filters\LogsFilter->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
 4 SYSTEMPATH/Filters/Filters.php(225): CodeIgniter\Filters\Filters->runAfter([...])
 5 SYSTEMPATH/CodeIgniter.php(525): CodeIgniter\Filters\Filters->run('leads', 'after')
 6 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-12 18:35:34 --> CodeIgniter\Exceptions\InvalidArgumentException: update(): argument #1 ($id) should not be boolean.
[Method: GET, Route: leads]
in SYSTEMPATH/BaseModel.php on line 989.
 1 SYSTEMPATH/Model.php(863): CodeIgniter\BaseModel->update(false, [...])
 2 APPPATH/Filters/LogsFilter.php(63): CodeIgniter\Model->update(false, [...])
 3 SYSTEMPATH/Filters/Filters.php(278): App\Filters\LogsFilter->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
 4 SYSTEMPATH/Filters/Filters.php(225): CodeIgniter\Filters\Filters->runAfter([...])
 5 SYSTEMPATH/CodeIgniter.php(525): CodeIgniter\Filters\Filters->run('leads', 'after')
 6 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-12 18:43:17 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in /var/www/api/system/Database/MySQLi/Connection.php:327
Stack trace:
#0 /var/www/api/system/Database/MySQLi/Connection.php(327): mysqli->query('INSERT INTO `lo...', 0)
#1 /var/www/api/system/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/api/system/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/api/system/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/api/system/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/api/system/BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 /var/www/api/system/Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 /var/www/api/app/Filters/LogsFilter.php(41): CodeIgniter\Model->insert(Array)
#8 /var/www/api/system/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#9 /var/www/api/system/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore(Array)
#10 /var/www/api/system/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
#11 /var/www/api/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/api/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 /var/www/api/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-04-12 18:43:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: GET, Route: leads]
in SYSTEMPATH/Database/BaseConnection.php on line 692.
 1 SYSTEMPATH/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (:ip:, :uri:, :method:, :headers:, :body:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH/Filters/LogsFilter.php(41): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 7 SYSTEMPATH/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore([...])
 8 SYSTEMPATH/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
 9 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-12 18:43:18 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 332.
 1 SYSTEMPATH/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (\'172.18.0.1\', \'http://localhost/api/index.php/leads\', \'GET\', \'{\\"Connection\\":{},\\"Accept-Encoding\\":{},\\"Host\\":{},\\"Postman-Token\\":{},\\"Accept\\":{},\\"User-Agent\\":{},\\"Authorization\\":{}}\', \'null\', \'2025-04-12 18:43:17\', \'2025-04-12 18:43:17\')')
 2 SYSTEMPATH/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (\'172.18.0.1\', \'http://localhost/api/index.php/leads\', \'GET\', \'{\\"Connection\\":{},\\"Accept-Encoding\\":{},\\"Host\\":{},\\"Postman-Token\\":{},\\"Accept\\":{},\\"User-Agent\\":{},\\"Authorization\\":{}}\', \'null\', \'2025-04-12 18:43:17\', \'2025-04-12 18:43:17\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (:ip:, :uri:, :method:, :headers:, :body:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH/Filters/LogsFilter.php(41): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 9 SYSTEMPATH/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore([...])
10 SYSTEMPATH/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
11 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-12 18:43:18 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 327.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(327): mysqli->query('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (\'172.18.0.1\', \'http://localhost/api/index.php/leads\', \'GET\', \'{\\"Connection\\":{},\\"Accept-Encoding\\":{},\\"Host\\":{},\\"Postman-Token\\":{},\\"Accept\\":{},\\"User-Agent\\":{},\\"Authorization\\":{}}\', \'null\', \'2025-04-12 18:43:17\', \'2025-04-12 18:43:17\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (\'172.18.0.1\', \'http://localhost/api/index.php/leads\', \'GET\', \'{\\"Connection\\":{},\\"Accept-Encoding\\":{},\\"Host\\":{},\\"Postman-Token\\":{},\\"Accept\\":{},\\"User-Agent\\":{},\\"Authorization\\":{}}\', \'null\', \'2025-04-12 18:43:17\', \'2025-04-12 18:43:17\')')
 3 SYSTEMPATH/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (\'172.18.0.1\', \'http://localhost/api/index.php/leads\', \'GET\', \'{\\"Connection\\":{},\\"Accept-Encoding\\":{},\\"Host\\":{},\\"Postman-Token\\":{},\\"Accept\\":{},\\"User-Agent\\":{},\\"Authorization\\":{}}\', \'null\', \'2025-04-12 18:43:17\', \'2025-04-12 18:43:17\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (:ip:, :uri:, :method:, :headers:, :body:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH/Filters/LogsFilter.php(41): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
10 SYSTEMPATH/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore([...])
11 SYSTEMPATH/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
12 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-12 19:14:56 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in /var/www/api/system/Database/MySQLi/Connection.php:327
Stack trace:
#0 /var/www/api/system/Database/MySQLi/Connection.php(327): mysqli->query('INSERT INTO `lo...', 0)
#1 /var/www/api/system/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/api/system/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/api/system/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/api/system/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/api/system/BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 /var/www/api/system/Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 /var/www/api/app/Filters/LogsFilter.php(42): CodeIgniter\Model->insert(Array)
#8 /var/www/api/system/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#9 /var/www/api/system/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore(Array)
#10 /var/www/api/system/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
#11 /var/www/api/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/api/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 /var/www/api/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-04-12 19:14:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: leads]
in SYSTEMPATH/Database/BaseConnection.php on line 692.
 1 SYSTEMPATH/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (:ip:, :uri:, :method:, :headers:, :body:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH/Filters/LogsFilter.php(42): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 7 SYSTEMPATH/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore([...])
 8 SYSTEMPATH/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
 9 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-12 19:14:56 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 332.
 1 SYSTEMPATH/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (\'172.18.0.1\', \'leads\', \'POST\', \'{\\"Content-Type\\":{},\\"Content-Length\\":{},\\"Connection\\":{},\\"Accept-Encoding\\":{},\\"Host\\":{},\\"Postman-Token\\":{},\\"Accept\\":{},\\"User-Agent\\":{},\\"Authorization\\":{}}\', \'{\\"id\\":5,\\"first_name\\":\\"Waldon\\",\\"last_name\\":\\"McPeake\\",\\"email\\":\\"wmcpeake4@cdc.gov\\",\\"phone\\":\\"111-979-1860\\",\\"birthdate\\":\\"2002-10-13\\"}\', \'2025-04-12 19:14:55\', \'2025-04-12 19:14:55\')')
 2 SYSTEMPATH/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (\'172.18.0.1\', \'leads\', \'POST\', \'{\\"Content-Type\\":{},\\"Content-Length\\":{},\\"Connection\\":{},\\"Accept-Encoding\\":{},\\"Host\\":{},\\"Postman-Token\\":{},\\"Accept\\":{},\\"User-Agent\\":{},\\"Authorization\\":{}}\', \'{\\"id\\":5,\\"first_name\\":\\"Waldon\\",\\"last_name\\":\\"McPeake\\",\\"email\\":\\"wmcpeake4@cdc.gov\\",\\"phone\\":\\"111-979-1860\\",\\"birthdate\\":\\"2002-10-13\\"}\', \'2025-04-12 19:14:55\', \'2025-04-12 19:14:55\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (:ip:, :uri:, :method:, :headers:, :body:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH/Filters/LogsFilter.php(42): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 9 SYSTEMPATH/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore([...])
10 SYSTEMPATH/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
11 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-12 19:14:56 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 327.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(327): mysqli->query('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (\'172.18.0.1\', \'leads\', \'POST\', \'{\\"Content-Type\\":{},\\"Content-Length\\":{},\\"Connection\\":{},\\"Accept-Encoding\\":{},\\"Host\\":{},\\"Postman-Token\\":{},\\"Accept\\":{},\\"User-Agent\\":{},\\"Authorization\\":{}}\', \'{\\"id\\":5,\\"first_name\\":\\"Waldon\\",\\"last_name\\":\\"McPeake\\",\\"email\\":\\"wmcpeake4@cdc.gov\\",\\"phone\\":\\"111-979-1860\\",\\"birthdate\\":\\"2002-10-13\\"}\', \'2025-04-12 19:14:55\', \'2025-04-12 19:14:55\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (\'172.18.0.1\', \'leads\', \'POST\', \'{\\"Content-Type\\":{},\\"Content-Length\\":{},\\"Connection\\":{},\\"Accept-Encoding\\":{},\\"Host\\":{},\\"Postman-Token\\":{},\\"Accept\\":{},\\"User-Agent\\":{},\\"Authorization\\":{}}\', \'{\\"id\\":5,\\"first_name\\":\\"Waldon\\",\\"last_name\\":\\"McPeake\\",\\"email\\":\\"wmcpeake4@cdc.gov\\",\\"phone\\":\\"111-979-1860\\",\\"birthdate\\":\\"2002-10-13\\"}\', \'2025-04-12 19:14:55\', \'2025-04-12 19:14:55\')')
 3 SYSTEMPATH/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (\'172.18.0.1\', \'leads\', \'POST\', \'{\\"Content-Type\\":{},\\"Content-Length\\":{},\\"Connection\\":{},\\"Accept-Encoding\\":{},\\"Host\\":{},\\"Postman-Token\\":{},\\"Accept\\":{},\\"User-Agent\\":{},\\"Authorization\\":{}}\', \'{\\"id\\":5,\\"first_name\\":\\"Waldon\\",\\"last_name\\":\\"McPeake\\",\\"email\\":\\"wmcpeake4@cdc.gov\\",\\"phone\\":\\"111-979-1860\\",\\"birthdate\\":\\"2002-10-13\\"}\', \'2025-04-12 19:14:55\', \'2025-04-12 19:14:55\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (:ip:, :uri:, :method:, :headers:, :body:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH/Filters/LogsFilter.php(42): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
10 SYSTEMPATH/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore([...])
11 SYSTEMPATH/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
12 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-12 19:26:29 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in /var/www/api/system/Database/MySQLi/Connection.php:327
Stack trace:
#0 /var/www/api/system/Database/MySQLi/Connection.php(327): mysqli->query('INSERT INTO `lo...', 0)
#1 /var/www/api/system/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/api/system/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/api/system/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/api/system/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/api/system/BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 /var/www/api/system/Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 /var/www/api/app/Filters/LogsFilter.php(42): CodeIgniter\Model->insert(Array)
#8 /var/www/api/system/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#9 /var/www/api/system/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore(Array)
#10 /var/www/api/system/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
#11 /var/www/api/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/api/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 /var/www/api/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-04-12 19:26:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: leads]
in SYSTEMPATH/Database/BaseConnection.php on line 692.
 1 SYSTEMPATH/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (:ip:, :uri:, :method:, :headers:, :body:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH/Filters/LogsFilter.php(42): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 7 SYSTEMPATH/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore([...])
 8 SYSTEMPATH/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
 9 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-12 19:26:29 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 332.
 1 SYSTEMPATH/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (\'172.18.0.1\', \'leads\', \'POST\', \'{\\"Content-Type\\":{},\\"Content-Length\\":{},\\"Connection\\":{},\\"Accept-Encoding\\":{},\\"Host\\":{},\\"Postman-Token\\":{},\\"Accept\\":{},\\"User-Agent\\":{},\\"Authorization\\":{}}\', \'{\\"id\\":5,\\"first_name\\":\\"Waldon\\",\\"last_name\\":\\"McPeake\\",\\"email\\":\\"wmcpeake4@cdc.gov\\",\\"phone\\":\\"111-979-1860\\",\\"birthdate\\":\\"2002-10-13\\"}\', \'2025-04-12 19:26:29\', \'2025-04-12 19:26:29\')')
 2 SYSTEMPATH/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (\'172.18.0.1\', \'leads\', \'POST\', \'{\\"Content-Type\\":{},\\"Content-Length\\":{},\\"Connection\\":{},\\"Accept-Encoding\\":{},\\"Host\\":{},\\"Postman-Token\\":{},\\"Accept\\":{},\\"User-Agent\\":{},\\"Authorization\\":{}}\', \'{\\"id\\":5,\\"first_name\\":\\"Waldon\\",\\"last_name\\":\\"McPeake\\",\\"email\\":\\"wmcpeake4@cdc.gov\\",\\"phone\\":\\"111-979-1860\\",\\"birthdate\\":\\"2002-10-13\\"}\', \'2025-04-12 19:26:29\', \'2025-04-12 19:26:29\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (:ip:, :uri:, :method:, :headers:, :body:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH/Filters/LogsFilter.php(42): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 9 SYSTEMPATH/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore([...])
10 SYSTEMPATH/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
11 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-12 19:26:29 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 327.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(327): mysqli->query('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (\'172.18.0.1\', \'leads\', \'POST\', \'{\\"Content-Type\\":{},\\"Content-Length\\":{},\\"Connection\\":{},\\"Accept-Encoding\\":{},\\"Host\\":{},\\"Postman-Token\\":{},\\"Accept\\":{},\\"User-Agent\\":{},\\"Authorization\\":{}}\', \'{\\"id\\":5,\\"first_name\\":\\"Waldon\\",\\"last_name\\":\\"McPeake\\",\\"email\\":\\"wmcpeake4@cdc.gov\\",\\"phone\\":\\"111-979-1860\\",\\"birthdate\\":\\"2002-10-13\\"}\', \'2025-04-12 19:26:29\', \'2025-04-12 19:26:29\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (\'172.18.0.1\', \'leads\', \'POST\', \'{\\"Content-Type\\":{},\\"Content-Length\\":{},\\"Connection\\":{},\\"Accept-Encoding\\":{},\\"Host\\":{},\\"Postman-Token\\":{},\\"Accept\\":{},\\"User-Agent\\":{},\\"Authorization\\":{}}\', \'{\\"id\\":5,\\"first_name\\":\\"Waldon\\",\\"last_name\\":\\"McPeake\\",\\"email\\":\\"wmcpeake4@cdc.gov\\",\\"phone\\":\\"111-979-1860\\",\\"birthdate\\":\\"2002-10-13\\"}\', \'2025-04-12 19:26:29\', \'2025-04-12 19:26:29\')')
 3 SYSTEMPATH/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (\'172.18.0.1\', \'leads\', \'POST\', \'{\\"Content-Type\\":{},\\"Content-Length\\":{},\\"Connection\\":{},\\"Accept-Encoding\\":{},\\"Host\\":{},\\"Postman-Token\\":{},\\"Accept\\":{},\\"User-Agent\\":{},\\"Authorization\\":{}}\', \'{\\"id\\":5,\\"first_name\\":\\"Waldon\\",\\"last_name\\":\\"McPeake\\",\\"email\\":\\"wmcpeake4@cdc.gov\\",\\"phone\\":\\"111-979-1860\\",\\"birthdate\\":\\"2002-10-13\\"}\', \'2025-04-12 19:26:29\', \'2025-04-12 19:26:29\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logs` (`ip`, `uri`, `method`, `headers`, `body`, `created_at`, `updated_at`) VALUES (:ip:, :uri:, :method:, :headers:, :body:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH/Filters/LogsFilter.php(42): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
10 SYSTEMPATH/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore([...])
11 SYSTEMPATH/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
12 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-12 19:27:43 --> mysqli_sql_exception: Unknown column 'ss' in 'field list' in /var/www/api/system/Database/MySQLi/Connection.php:327
Stack trace:
#0 /var/www/api/system/Database/MySQLi/Connection.php(327): mysqli->query('INSERT INTO `le...', 0)
#1 /var/www/api/system/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 /var/www/api/system/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 /var/www/api/system/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 /var/www/api/system/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/api/system/BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 /var/www/api/system/Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 /var/www/api/app/Controllers/Leads.php(62): CodeIgniter\Model->insert(Array)
#8 /var/www/api/system/CodeIgniter.php(933): App\Controllers\Leads->create()
#9 /var/www/api/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Leads))
#10 /var/www/api/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/api/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 /var/www/api/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-04-12 19:29:40 --> mysqli_sql_exception: Unknown column 'ss' in 'field list' in /var/www/api/system/Database/MySQLi/Connection.php:327
Stack trace:
#0 /var/www/api/system/Database/MySQLi/Connection.php(327): mysqli->query('INSERT INTO `le...', 0)
#1 /var/www/api/system/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 /var/www/api/system/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 /var/www/api/system/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 /var/www/api/system/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/api/system/BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 /var/www/api/system/Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 /var/www/api/app/Controllers/Leads.php(64): CodeIgniter\Model->insert(Array)
#8 /var/www/api/system/CodeIgniter.php(933): App\Controllers\Leads->create()
#9 /var/www/api/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Leads))
#10 /var/www/api/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/api/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 /var/www/api/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-04-12 19:37:39 --> mysqli_sql_exception: Unknown column 'asd' in 'field list' in /var/www/api/system/Database/MySQLi/Connection.php:327
Stack trace:
#0 /var/www/api/system/Database/MySQLi/Connection.php(327): mysqli->query('INSERT INTO `lo...', 0)
#1 /var/www/api/system/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/api/system/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/api/system/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/api/system/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/api/system/BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 /var/www/api/system/Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 /var/www/api/app/Filters/LogsFilter.php(43): CodeIgniter\Model->insert(Array)
#8 /var/www/api/system/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#9 /var/www/api/system/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore(Array)
#10 /var/www/api/system/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
#11 /var/www/api/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/api/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 /var/www/api/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
ERROR - 2025-04-12 19:37:40 --> mysqli_sql_exception: Unknown column 'ss' in 'field list' in /var/www/api/system/Database/MySQLi/Connection.php:327
Stack trace:
#0 /var/www/api/system/Database/MySQLi/Connection.php(327): mysqli->query('INSERT INTO `le...', 0)
#1 /var/www/api/system/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 /var/www/api/system/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 /var/www/api/system/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 /var/www/api/system/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/api/system/BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 /var/www/api/system/Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 /var/www/api/app/Controllers/Leads.php(64): CodeIgniter\Model->insert(Array)
#8 /var/www/api/system/CodeIgniter.php(933): App\Controllers\Leads->create()
#9 /var/www/api/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Leads))
#10 /var/www/api/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/api/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 /var/www/api/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-04-12 19:37:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Updates are not allowed unless they contain a "where" or "like" clause.
[Method: POST, Route: leads]
in SYSTEMPATH/Model.php on line 456.
 1 SYSTEMPATH/BaseModel.php(1027): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH/Model.php(863): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH/Filters/LogsFilter.php(83): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH/Filters/Filters.php(278): App\Filters\LogsFilter->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
 5 SYSTEMPATH/Filters/Filters.php(225): CodeIgniter\Filters\Filters->runAfter([...])
 6 SYSTEMPATH/CodeIgniter.php(525): CodeIgniter\Filters\Filters->run('leads', 'after')
 7 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-04-12 19:38:13 --> mysqli_sql_exception: Unknown column 'asd' in 'field list' in /var/www/api/system/Database/MySQLi/Connection.php:327
Stack trace:
#0 /var/www/api/system/Database/MySQLi/Connection.php(327): mysqli->query('INSERT INTO `lo...', 0)
#1 /var/www/api/system/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/api/system/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/api/system/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/api/system/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/api/system/BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 /var/www/api/system/Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 /var/www/api/app/Filters/LogsFilter.php(43): CodeIgniter\Model->insert(Array)
#8 /var/www/api/system/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#9 /var/www/api/system/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore(Array)
#10 /var/www/api/system/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
#11 /var/www/api/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/api/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 /var/www/api/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
ERROR - 2025-04-12 19:39:13 --> mysqli_sql_exception: Unknown column 'asd' in 'field list' in /var/www/api/system/Database/MySQLi/Connection.php:327
Stack trace:
#0 /var/www/api/system/Database/MySQLi/Connection.php(327): mysqli->query('INSERT INTO `lo...', 0)
#1 /var/www/api/system/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/api/system/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/api/system/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/api/system/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/api/system/BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 /var/www/api/system/Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 /var/www/api/app/Filters/LogsFilter.php(43): CodeIgniter\Model->insert(Array)
#8 /var/www/api/system/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#9 /var/www/api/system/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore(Array)
#10 /var/www/api/system/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
#11 /var/www/api/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/api/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 /var/www/api/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
ERROR - 2025-04-12 19:39:18 --> mysqli_sql_exception: Unknown column 'asd' in 'field list' in /var/www/api/system/Database/MySQLi/Connection.php:327
Stack trace:
#0 /var/www/api/system/Database/MySQLi/Connection.php(327): mysqli->query('INSERT INTO `lo...', 0)
#1 /var/www/api/system/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/api/system/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/api/system/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/api/system/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/api/system/BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 /var/www/api/system/Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 /var/www/api/app/Filters/LogsFilter.php(43): CodeIgniter\Model->insert(Array)
#8 /var/www/api/system/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#9 /var/www/api/system/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore(Array)
#10 /var/www/api/system/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
#11 /var/www/api/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/api/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 /var/www/api/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
ERROR - 2025-04-12 19:39:36 --> mysqli_sql_exception: Unknown column 'asd' in 'field list' in /var/www/api/system/Database/MySQLi/Connection.php:327
Stack trace:
#0 /var/www/api/system/Database/MySQLi/Connection.php(327): mysqli->query('INSERT INTO `lo...', 0)
#1 /var/www/api/system/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/api/system/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/api/system/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/api/system/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/api/system/BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 /var/www/api/system/Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 /var/www/api/app/Filters/LogsFilter.php(43): CodeIgniter\Model->insert(Array)
#8 /var/www/api/system/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#9 /var/www/api/system/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore(Array)
#10 /var/www/api/system/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
#11 /var/www/api/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/api/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 /var/www/api/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
ERROR - 2025-04-12 19:40:40 --> mysqli_sql_exception: Unknown column 'asd' in 'field list' in /var/www/api/system/Database/MySQLi/Connection.php:327
Stack trace:
#0 /var/www/api/system/Database/MySQLi/Connection.php(327): mysqli->query('INSERT INTO `lo...', 0)
#1 /var/www/api/system/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/api/system/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/api/system/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/api/system/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/api/system/BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 /var/www/api/system/Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 /var/www/api/app/Filters/LogsFilter.php(43): CodeIgniter\Model->insert(Array)
#8 /var/www/api/system/Filters/Filters.php(241): App\Filters\LogsFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#9 /var/www/api/system/Filters/Filters.php(221): CodeIgniter\Filters\Filters->runBefore(Array)
#10 /var/www/api/system/CodeIgniter.php(479): CodeIgniter\Filters\Filters->run('leads', 'before')
#11 /var/www/api/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/api/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 /var/www/api/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
ERROR - 2025-04-12 19:40:56 --> mysqli_sql_exception: Unknown column 'ss' in 'field list' in /var/www/api/system/Database/MySQLi/Connection.php:327
Stack trace:
#0 /var/www/api/system/Database/MySQLi/Connection.php(327): mysqli->query('INSERT INTO `le...', 0)
#1 /var/www/api/system/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 /var/www/api/system/Database/BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 /var/www/api/system/Database/BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 /var/www/api/system/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/api/system/BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 /var/www/api/system/Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 /var/www/api/app/Controllers/Leads.php(64): CodeIgniter\Model->insert(Array)
#8 /var/www/api/system/CodeIgniter.php(933): App\Controllers\Leads->create()
#9 /var/www/api/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Leads))
#10 /var/www/api/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/api/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 /var/www/api/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /var/www/api/public/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-04-12 23:23:09 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "leads_import_form.php"
[Method: GET, Route: /]
in SYSTEMPATH/Exceptions/FrameworkException.php on line 39.
 1 SYSTEMPATH/View/View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('leads_import_form.php')
 2 SYSTEMPATH/Common.php(1173): CodeIgniter\View\View->render('leads_import_form', [], true)
 3 APPPATH/Controllers/Home.php(9): view('leads_import_form')
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Home->index()
 5 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-04-12 23:24:33 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "leads_import_form.php"
[Method: GET, Route: /]
in SYSTEMPATH/Exceptions/FrameworkException.php on line 39.
 1 SYSTEMPATH/View/View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('leads_import_form.php')
 2 SYSTEMPATH/Common.php(1173): CodeIgniter\View\View->render('leads_import_form', [], true)
 3 APPPATH/Controllers/Home.php(9): view('leads_import_form')
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Home->index()
 5 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
